/**
 * Common Type Definitions
 * 
 * These base types are used across the entire platform.
 * Keep these minimal to reduce duplication.
 */

/** UUID identifier (generated by PostgreSQL or application) */
export type UUID = string & { readonly __brand: 'UUID' };

/** ISO 8601 timestamp */
export type Timestamp = Date;

/** Plan types determine feature access and pricing model */
export type PlanType = 'free' | 'pro' | 'paygo';

/** HTTP error response structure - standardized across all services */
export interface ErrorResponse {
  ok: false;
  error: {
    code: string;
    message: string;
    details?: Record<string, any>;
  };
}

/** Success response wrapper - used for all API responses */
export interface SuccessResponse<T> {
  ok: true;
  data:  T;
}

/** Generic API response type */
export type ApiResponse<T> = SuccessResponse<T> | ErrorResponse;

/** Pagination metadata */
export interface Pagination {
  page: number;
  limit: number;
  total: number;
  pages: number;
}

/** Paginated list response */
export interface PaginatedResponse<T> {
  ok: true;
  data: T[];
  pagination: Pagination;
}

/** Health check response for service readiness */
export interface HealthResponse {
  ok: true;
  service: string;
  version: string;
  timestamp: string;
}