/**
 * GEKO-AI PostgreSQL Initialization
 * 
 * Creates all tables, indexes, and constraints for multi-tenant platform
 * 
 * Design principles:
 * - All tables have tenantId for isolation
 * - UUIDs for all IDs (generated by PostgreSQL)
 * - Timestamps for audit trails
 * - Foreign keys enforce referential integrity
 * - Indexes on common queries
 */

-- Create extensions
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- ============================================================
-- TENANT & USER MANAGEMENT
-- ============================================================

/**
 * Tenants:  Isolated organizations
 * All data is scoped to a tenant
 */
CREATE TABLE IF NOT EXISTS tenants (
  tenantId UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  name VARCHAR(255) NOT NULL,
  slug VARCHAR(255) UNIQUE NOT NULL,
  status VARCHAR(50) DEFAULT 'active',
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_tenants_slug ON tenants(slug);
CREATE INDEX idx_tenants_status ON tenants(status);

/**
 * Users: Belong to tenants
 * Identity is (tenantId, userId)
 */
CREATE TABLE IF NOT EXISTS users (
  userId UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  tenantId UUID NOT NULL REFERENCES tenants(tenantId) ON DELETE CASCADE,
  email VARCHAR(255) NOT NULL,
  passwordHash VARCHAR(255) NOT NULL,
  firstName VARCHAR(255),
  lastName VARCHAR(255),
  emailVerified BOOLEAN DEFAULT FALSE,
  status VARCHAR(50) DEFAULT 'active',
  lastLoginAt TIMESTAMP,
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UNIQUE(tenantId, email)
);

CREATE INDEX idx_users_tenantId ON users(tenantId);
CREATE INDEX idx_users_email ON users(email);
CREATE INDEX idx_users_status ON users(status);

-- ============================================================
-- WORKSPACES & TEAM MANAGEMENT
-- ============================================================

/**
 * Workspaces: Teams within a tenant
 * Each workspace has its own settings, members, quotas
 */
CREATE TABLE IF NOT EXISTS workspaces (
  workspaceId UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  tenantId UUID NOT NULL REFERENCES tenants(tenantId) ON DELETE CASCADE,
  name VARCHAR(255) NOT NULL,
  description TEXT,
  plan VARCHAR(50) DEFAULT 'free', -- free, pro, paygo
  status VARCHAR(50) DEFAULT 'active',
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_workspaces_tenantId ON workspaces(tenantId);
CREATE INDEX idx_workspaces_plan ON workspaces(plan);
CREATE INDEX idx_workspaces_status ON workspaces(status);

/**
 * Workspace Members: Users in workspaces with roles
 * Allows same user in multiple workspaces with different roles
 */
CREATE TABLE IF NOT EXISTS workspace_members (
  memberId UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  workspaceId UUID NOT NULL REFERENCES workspaces(workspaceId) ON DELETE CASCADE,
  userId UUID NOT NULL REFERENCES users(userId) ON DELETE CASCADE,
  role VARCHAR(50) NOT NULL, -- owner, admin, editor, viewer
  joinedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  invitedBy UUID REFERENCES users(userId),
  UNIQUE(workspaceId, userId)
);

CREATE INDEX idx_workspace_members_workspaceId ON workspace_members(workspaceId);
CREATE INDEX idx_workspace_members_userId ON workspace_members(userId);
CREATE INDEX idx_workspace_members_role ON workspace_members(role);

/**
 * Workspace Invitations: Pending member invites
 * Token-based, with expiration
 */
CREATE TABLE IF NOT EXISTS workspace_invites (
  inviteId UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  workspaceId UUID NOT NULL REFERENCES workspaces(workspaceId) ON DELETE CASCADE,
  email VARCHAR(255) NOT NULL,
  role VARCHAR(50) NOT NULL,
  token VARCHAR(255) UNIQUE NOT NULL,
  expiresAt TIMESTAMP NOT NULL,
  acceptedAt TIMESTAMP,
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_workspace_invites_token ON workspace_invites(token);
CREATE INDEX idx_workspace_invites_workspaceId ON workspace_invites(workspaceId);

-- ============================================================
-- RBAC (ROLE-BASED ACCESS CONTROL)
-- ============================================================

/**
 * Roles: Per-workspace role definitions
 * Each workspace can have custom roles
 */
CREATE TABLE IF NOT EXISTS roles (
  roleId UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  workspaceId UUID NOT NULL REFERENCES workspaces(workspaceId) ON DELETE CASCADE,
  name VARCHAR(50) NOT NULL, -- owner, admin, editor, viewer
  description TEXT,
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UNIQUE(workspaceId, name)
);

CREATE INDEX idx_roles_workspaceId ON roles(workspaceId);

/**
 * Permissions:  Granular actions (e.g., 'chat:create', 'model:use_premium')
 * Linked to roles
 */
CREATE TABLE IF NOT EXISTS permissions (
  permissionId UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  roleId UUID NOT NULL REFERENCES roles(roleId) ON DELETE CASCADE,
  permission VARCHAR(255) NOT NULL,
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_permissions_roleId ON permissions(roleId);
CREATE INDEX idx_permissions_permission ON permissions(permission);

-- ============================================================
-- MODEL MANAGEMENT
-- ============================================================

/**
 * Model Catalog: All available AI models (global)
 * Read-only, updated by admin
 */
CREATE TABLE IF NOT EXISTS model_catalog (
  catalogId UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  modelId VARCHAR(255) NOT NULL UNIQUE,
  provider VARCHAR(50) NOT NULL, -- openai, anthropic, google, deepseek, ollama
  displayName VARCHAR(255) NOT NULL,
  description TEXT,
  costPerMInputTokens DECIMAL(10, 8) NOT NULL DEFAULT 0,
  costPerMOutputTokens DECIMAL(10, 8) NOT NULL DEFAULT 0,
  minPlan VARCHAR(50) DEFAULT 'free', -- free, pro, paygo
  isLocal BOOLEAN DEFAULT FALSE,
  isFreeTier BOOLEAN DEFAULT FALSE,
  freeTierTokensPerMonth INTEGER,
  freeTierRequestsPerMonth INTEGER,
  releasedAt TIMESTAMP NOT NULL,
  deprecatedAt TIMESTAMP,
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_model_catalog_provider ON model_catalog(provider);
CREATE INDEX idx_model_catalog_minPlan ON model_catalog(minPlan);
CREATE INDEX idx_model_catalog_isLocal ON model_catalog(isLocal);

/**
 * Workspace Models: Per-workspace model configuration
 * Allows enabling/disabling models per workspace
 */
CREATE TABLE IF NOT EXISTS workspace_models (
  workspaceModelId UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  workspaceId UUID NOT NULL REFERENCES workspaces(workspaceId) ON DELETE CASCADE,
  modelId VARCHAR(255) NOT NULL,
  enabled BOOLEAN DEFAULT TRUE,
  costOverride DECIMAL(10, 8),
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (modelId) REFERENCES model_catalog(modelId),
  UNIQUE(workspaceId, modelId)
);

CREATE INDEX idx_workspace_models_workspaceId ON workspace_models(workspaceId);
CREATE INDEX idx_workspace_models_enabled ON workspace_models(enabled);

/**
 * Local Model Status: Track local model installations
 */
CREATE TABLE IF NOT EXISTS local_model_status (
  statusId UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  workspaceId UUID NOT NULL REFERENCES workspaces(workspaceId) ON DELETE CASCADE,
  modelId VARCHAR(255) NOT NULL,
  status VARCHAR(50) NOT NULL, -- notInstalled, downloading, ready, error
  progress INTEGER,
  errorMessage TEXT,
  installedSizeMb INTEGER,
  lastChecked TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UNIQUE(workspaceId, modelId)
);

CREATE INDEX idx_local_model_status_workspaceId ON local_model_status(workspaceId);
CREATE INDEX idx_local_model_status_status ON local_model_status(status);

-- ============================================================
-- BILLING & QUOTAS
-- ============================================================

/**
 * Subscriptions:  Workspace billing plans
 * Tracks plan type, payment info, current month cost
 */
CREATE TABLE IF NOT EXISTS subscriptions (
  subscriptionId UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  workspaceId UUID NOT NULL UNIQUE REFERENCES workspaces(workspaceId) ON DELETE CASCADE,
  tenantId UUID NOT NULL REFERENCES tenants(tenantId) ON DELETE CASCADE,
  plan VARCHAR(50) NOT NULL, -- free, pro, paygo
  status VARCHAR(50) DEFAULT 'active', -- active, paused, cancelled
  stripeCustomerId VARCHAR(255),
  stripeSubscriptionId VARCHAR(255),
  currentMonthCost DECIMAL(12, 2) DEFAULT 0,
  budgetLimit DECIMAL(12, 2),
  startedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  renewedAt TIMESTAMP,
  cancelledAt TIMESTAMP,
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_subscriptions_workspaceId ON subscriptions(workspaceId);
CREATE INDEX idx_subscriptions_plan ON subscriptions(plan);
CREATE INDEX idx_subscriptions_status ON subscriptions(status);

/**
 * Quotas: Token/request limits per workspace per month
 * Reset monthly
 */
CREATE TABLE IF NOT EXISTS quotas (
  quotaId UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  workspaceId UUID NOT NULL UNIQUE REFERENCES workspaces(workspaceId) ON DELETE CASCADE,
  tokensLimitPerMonth INTEGER NOT NULL,
  requestsLimitPerMonth INTEGER NOT NULL,
  tokensUsedThisMonth INTEGER DEFAULT 0,
  requestsUsedThisMonth INTEGER DEFAULT 0,
  resetAt TIMESTAMP NOT NULL,
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_quotas_workspaceId ON quotas(workspaceId);
CREATE INDEX idx_quotas_resetAt ON quotas(resetAt);

/**
 * Token Usage: Every AI API call logged for billing
 */
CREATE TABLE IF NOT EXISTS token_usage (
  usageId UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  workspaceId UUID NOT NULL REFERENCES workspaces(workspaceId) ON DELETE CASCADE,
  userId UUID NOT NULL REFERENCES users(userId) ON DELETE CASCADE,
  modelId VARCHAR(255) NOT NULL,
  conversationId VARCHAR(255),
  inputTokens INTEGER NOT NULL DEFAULT 0,
  outputTokens INTEGER NOT NULL DEFAULT 0,
  costToUs DECIMAL(12, 8) NOT NULL DEFAULT 0,
  chargeToUser DECIMAL(12, 8) NOT NULL DEFAULT 0,
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_token_usage_workspaceId ON token_usage(workspaceId);
CREATE INDEX idx_token_usage_userId ON token_usage(userId);
CREATE INDEX idx_token_usage_modelId ON token_usage(modelId);
CREATE INDEX idx_token_usage_createdAt ON token_usage(createdAt);
CREATE INDEX idx_token_usage_month ON token_usage(workspaceId, DATE_TRUNC('month', createdAt));

/**
 * Monthly Usage: Aggregated usage per workspace per month
 * Denormalized for faster queries
 */
CREATE TABLE IF NOT EXISTS monthly_usage (
  usageId UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  workspaceId UUID NOT NULL REFERENCES workspaces(workspaceId) ON DELETE CASCADE,
  month VARCHAR(7) NOT NULL, -- "2024-01"
  totalTokens INTEGER DEFAULT 0,
  totalCostToUs DECIMAL(12, 2) DEFAULT 0,
  totalChargeToUser DECIMAL(12, 2) DEFAULT 0,
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UNIQUE(workspaceId, month)
);

CREATE INDEX idx_monthly_usage_workspaceId ON monthly_usage(workspaceId);
CREATE INDEX idx_monthly_usage_month ON monthly_usage(month);

/**
 * Invoices: Sent to customers for payment
 */
CREATE TABLE IF NOT EXISTS invoices (
  invoiceId UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  workspaceId UUID NOT NULL REFERENCES workspaces(workspaceId) ON DELETE CASCADE,
  tenantId UUID NOT NULL REFERENCES tenants(tenantId) ON DELETE CASCADE,
  stripeInvoiceId VARCHAR(255),
  amount DECIMAL(12, 2) NOT NULL,
  currency VARCHAR(3) DEFAULT 'usd',
  status VARCHAR(50) DEFAULT 'draft', -- draft, sent, paid, failed
  periodStart TIMESTAMP NOT NULL,
  periodEnd TIMESTAMP NOT NULL,
  dueDate TIMESTAMP NOT NULL,
  paidAt TIMESTAMP,
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_invoices_workspaceId ON invoices(workspaceId);
CREATE INDEX idx_invoices_status ON invoices(status);
CREATE INDEX idx_invoices_createdAt ON invoices(createdAt);

-- ============================================================
-- AUDIT LOGGING
-- ============================================================

/**
 * Audit Logs: Track all significant actions
 * For security, compliance, debugging
 */
CREATE TABLE IF NOT EXISTS audit_logs (
  auditLogId UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  tenantId UUID NOT NULL REFERENCES tenants(tenantId) ON DELETE CASCADE,
  workspaceId UUID REFERENCES workspaces(workspaceId) ON DELETE CASCADE,
  userId UUID REFERENCES users(userId) ON DELETE SET NULL,
  action VARCHAR(255) NOT NULL,
  resourceType VARCHAR(100) NOT NULL,
  resourceId VARCHAR(255) NOT NULL,
  changes JSONB,
  ipAddress VARCHAR(45),
  userAgent TEXT,
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_audit_logs_tenantId ON audit_logs(tenantId);
CREATE INDEX idx_audit_logs_workspaceId ON audit_logs(workspaceId);
CREATE INDEX idx_audit_logs_userId ON audit_logs(userId);
CREATE INDEX idx_audit_logs_action ON audit_logs(action);
CREATE INDEX idx_audit_logs_createdAt ON audit_logs(createdAt);

-- ============================================================
-- SESSIONS (for token revocation tracking)
-- ============================================================

/**
 * Sessions: Server-side session tracking
 * Enables token revocation, concurrent session limits
 */
CREATE TABLE IF NOT EXISTS sessions (
  sessionId UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  userId UUID NOT NULL REFERENCES users(userId) ON DELETE CASCADE,
  tenantId UUID NOT NULL REFERENCES tenants(tenantId) ON DELETE CASCADE,
  accessTokenHash VARCHAR(255) NOT NULL UNIQUE,
  refreshTokenHash VARCHAR(255),
  createdAt BIGINT NOT NULL, -- unix timestamp
  expiresAt BIGINT NOT NULL,
  ipAddress VARCHAR(45),
  userAgent TEXT,
  revokedAt BIGINT
);

CREATE INDEX idx_sessions_userId ON sessions(userId);
CREATE INDEX idx_sessions_tenantId ON sessions(tenantId);
CREATE INDEX idx_sessions_expiresAt ON sessions(expiresAt);
CREATE INDEX idx_sessions_revokedAt ON sessions(revokedAt);

-- ============================================================
-- PERMISSIONS & GRANTS
-- ============================================================

-- Grant all privileges to geko user
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO geko;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO geko;
GRANT USAGE ON SCHEMA public TO geko;

-- Enable RLS (Row Level Security) - optional for multi-tenancy
ALTER TABLE users ENABLE ROW LEVEL SECURITY;
ALTER TABLE workspaces ENABLE ROW LEVEL SECURITY;
ALTER TABLE workspace_members ENABLE ROW LEVEL SECURITY;
ALTER TABLE token_usage ENABLE ROW LEVEL SECURITY;
ALTER TABLE audit_logs ENABLE ROW LEVEL SECURITY;